### ISSUE TITLE
The gitblit module requires CentOS/RHEL 6 or newer

### ISSUE THREAD

**Issue by ltutar** [mgruener/puppet-gitblit#1]
Notice: /File[/opt/puppetlabs/puppet/cache/lib/shared/pe_server_version.rb]/ensure: defined content as '{md5}f3d3fc8776512ae73d3293c97b8f3dfe'
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, The gitblit module requires CentOS/RHEL 6 or newer at /etc/puppetlabs/code/environments/production/modules/gitblit/manifests/params.pp:36:20 on node gitblitagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

[root@gitblitagent ~]# facter -p operatingsystemmajrelease
7
[root@gitblitagent ~]# facter -p operatingsystem
CentOS
[root@gitblitagent ~]# 

please put the symbol ' between 6 and 7 in the case for CentOS

**Comment by mgruener** [comment]
Ah, facts are only treated as strings and my code uses integers...yes I will fix that, thanks.
