### ISSUE TITLE
java is needed but not installed with the puppet module

### ISSUE THREAD

**Issue by ltutar** [mgruener/puppet-gitblit#2]
gitblit is running as service after installing the jdk. it would be nice if the module also takes care of this.

**Comment by mgruener** [comment]
I am not so sure if I like this, as I do not see java to be "part" of gitblit.

There are other Puppet modules specifically to manage java, for example https://forge.puppetlabs.com/puppetlabs/java. Is there a reason why you do not want to use one of these modules?

**Comment by ltutar** [comment]
I am using puppetlabs/java actually. The empty README.MD surprised me. Maybe you can state it in the documentation that java is needed. I am used to modules working out-of-the-box.

---

java::distribution: 'jdk'
git::git:
gitblit::gitblit:
gitblit::install::staging::version: '1.6.2'
gitblit::adminpassword: 'benny'
gitblit::http_port: '8080'
gitblit::https_port: '0'

**Comment by mgruener** [comment]
Well I am hoping to get my modules to the point of "it just works" some day, but as I was the only person using them up till now (at least as far as I know) it is more of a "works for me situation" :laughing: 

Without the module being published on the puppet forge, there is no way to specify inter-module dependencies.

Would specifying the Java requirement in the readme solve the issue for you?

**Comment by ltutar** [comment]
I understand you. Specifying the Java requirement in the readme would solve my issue :)
