### ISSUE TITLE
make GITBLIT_BASE_FOLDER configurable in the ERB files

### ISSUE THREAD

**Issue by ltutar** [mgruener/puppet-gitblit#3]
It would be nice to define the value of GITBLIT_BASE_FOLDER in the erb files. It is now hardcoded.

GITBLIT_BASE_FOLDER=/opt/gitblit/data

**Comment by mgruener** [comment]
Thanks, good idea :)

**Comment by mgruener** [comment]
I just checked the code, the value for GITBLIT_BASE_FOLDER in gitblit.service.chkconfig.erb is just a default which can and should be overriden in source /etc/sysconfig/gitblit if necessary.

Is there a specific reason why you would like to override it in the ERB?

**Comment by mgruener** [comment]
Could you please answer my last question? If there is no specific reason, I would like to close the issue.

**Comment by ltutar** [comment]
You can close the issue. There is no reason to override it in the ERB.
