### ISSUE TITLE
gitblit::project are not visible in gitblit console

### ISSUE THREAD

**Issue by ltutar** [mgruener/puppet-gitblit#4]
When I have the following puppet code, the project is created but it is not visible in gitblit console.

  if $manage_gitblit_projects {
    gitblit::project { 'main':
      ensure      => present,
      name        => 'Main Repositories',
      description => 'main group of repositories',
      doc         => $mainprojectdoc
    }

```
gitblit::project { 'daddy':
  ensure      => present,
  name        => 'Daddy Repositories',
  description => 'daddy group of repositories',
  doc         => $mainprojectdoc
}
```

[root@gitblitagent git]# pwd
/var/lib/gitblit/git
[root@gitblitagent git]# ls
daddy  project.mkd
[root@gitblitagent git]# find .
.
./daddy
./project.mkd
[root@gitblitagent git]#

**Comment by ltutar** [comment]
Any idea about how I can create repository as shown in the attachment?

Thank you in advance.

![grabberraster 0935](https://cloud.githubusercontent.com/assets/7237078/10703465/a1ea1a32-79d0-11e5-9035-49d46ad5ad04.jpg)

**Comment by mgruener** [comment]
Regarding your screenshot, I am not quite sure what you want to achieve.
That projects do not appear in gitblit is strange but I never used or tested this functionality much ;)
I will leave this open till I find the time to investigate (Pull Requests welcome btw.)

**Comment by ltutar** [comment]
I want to create a project where I can also specify the access policy and select/deselect the other options like 'include a README'

**Comment by mgruener** [comment]
Ah, now I see. Sorry, this is not possible with gitblit. Projects are mere organizational units without any options attached.

The "Include a README" options and so on are part of the repository creation process and as far as I know these defaults can not be easily changed.

**Comment by ltutar** [comment]
thank you for your answer. I was also not able to find REST API's in gitblit documentation. I will sniff the http requests when creating the projects with the GUI. I want to fully automate the whole installation/configuration process.

**Comment by mgruener** [comment]
That would be one option if you want to automate it remotely. If you want to just automate it on the server itself, have a deeper look into the structure of the data folder. Gitblit is entirely textfile driven (although I do not remember the specific details), there is not database or binary datastore whatsoever.

**Comment by ltutar** [comment]
You can close this issue. 
The repo does not need to be created through Gitblit API.
When I run the following commands, the repository is visible in Gitblit. 

```
git remote add PetClinicDemo <%= @gitblit_server_protocol %>://<%= @gitblit_username %>:<%= @gitblit_password %>@<%= @gitblit_server_url %>/r/PetClinic.git
sleep 1
git push PetClinicDemo --all
```

**Comment by mgruener** [comment]
Nice to hear it works. Closing the issue.
