### ISSUE TITLE
HTTPS/SSL Certificate Management Support

### ISSUE THREAD

**Issue by FireDrunk** [mgruener/puppet-gitblit#8]
Is there any support (planned) for the management of the SSL key(store)'s?
Currently i can only manage the keystore manually, but it would be nice if we could do this thru the Puppet module.

**Comment by mgruener** [comment]
Could you please provide a more extensive description of your usecase? From what I see, it would be perfectly possible to manage the keystore with a specialiced module, for example with https://forge.puppetlabs.com/puppetlabs/java_ks without integrating it into this module.

I will gladly expand the module if you convince me of the advantages :smile:

**Comment by FireDrunk** [comment]
We're not using this module, but it seems like an appopriate option. Is their any example present for pointing the configuration to an existing certificate in the keystore?

(like the alias & password to use via hieradata)

**Comment by mgruener** [comment]
Sorry, no and I think this would also be out of scope right now. The documentation for puppetlabs/java_ks in combination with the gitblit documentation (http://gitblit.com/setup_go.html#H5) should provide enough information to create the necessary puppet code. 

Contact me at michael.gruener@chaosmoon.net if you still have trouble implementing the certificate handling :smile:
