### ISSUE TITLE
Ability to use hiera_merge only for Config

### ISSUE THREAD

**Issue by FireDrunk** [mgruener/puppet-gitblit#9]
It would be nice if i could use the hiera_merge variable only for the gitblit::config defined type.
I don't want to manage users, teams and projects with hiera, just the config, but when i set the hiera_merge parameter to true, i get hiera errors regarding the missing values for Users, Teams and Projects.

Thanks in advance!

**Comment by mgruener** [comment]
Have you tried setting these parameters in hiera to an empty hash?

```
---
gitblit::users: {}
gitblit::teams: {}
gitblit::projects: {}
```
